schema {
  query: Queries
  mutation: Mutation
}

type Book {
  title: String!
  authors: [String!]!
  description: String!
  isbn: String!
  thumbnailUri: String!
}

type Collection {
  id: ID!
  name: String!
  books: [String!]!
}

type TitleKeywords {
  keywords: String!
}

type AuthorKeywords {
  keywords: String!
}

type Keywords {
  titleKeywords: String!
  authorKeywords: String!
}

union SearchFilter = Keywords | AuthorKeywords | TitleKeywords

type Queries {
  books(searchFilter: SearchFilter!, results: Int = 10): [Book!]!
  book(isbn: String!): Book!
  collections: [Collection!]!
  collection(id: ID!): Collection!
}

type Mutations {
  createCollection(name: String!, books: [Book!]): Collection!
  deleteCollection(id: ID!): Collection!
  changeCollectionName(id: ID!, name: String!): Collection!
  addBook(id: ID!, book: Book!): Collection!
}
