name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Compile
        run: ./mill __.compile

      - name: Check Formatting
        run: ./mill __.checkFormat

      - name: Scalafix
        run: ./mill __.fix --check

      - name: Create docker Image
        run: ./mill finito.main.docker.build

      - name: Run tests
        run: ./mill __.test

      ##################
      # Coverage Stuff #
      ##################
      # https://github.com/codecov/codecov-action
      - name: Generate Coverage Reports
        run: ./mill scoverage.xmlReportAll

      - name: Send Coverage Reports
        uses: codecov/codecov-action@v5
        with:
          files: out/scoverage/xmlReportAll.dest/scoverage.xml
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      ####################
      # GH Release Stuff #
      ####################
      - name: Assembly
        if: startsWith(github.ref, 'refs/tags/')
        run: ./mill finito.main.assembly

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/finito/main/assembly.dest/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
